"""add_unique_to_payments

Revision ID: <auto-generated>
Revises: add_billing_accounts
Create Date: 2026-02-12
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers
revision = 'add_unique_to_payments'
down_revision = 'add_billing_accounts' # Links to your previous migration
branch_labels = None
depends_on = None

def upgrade():
    """
    Adds a UNIQUE constraint to (provider, external_reference).
    This prevents the same transaction from being processed twice.
    """
    op.create_unique_constraint(
        "unique_provider_reference",     # Name of the constraint
        "payment_transactions",          # Table name
        ["provider", "external_reference"] # Columns that must be unique together
    )

def downgrade():
    """
    Removes the unique constraint.
    """
    op.drop_constraint("unique_provider_reference", "payment_transactions", type_="unique")