"""add_billing_accounts

Revision ID: <auto-generated>
Revises: initial_setup
Create Date: 2026-02-11
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers
revision = 'add_billing_accounts'
down_revision = 'initial_setup' # Links to your previous migration
branch_labels = None
depends_on = None

def upgrade():
    # This table stores the actual "Wallet Balance" for each tenant
    op.execute("""
    CREATE TABLE billing_accounts (
        tenant_id TEXT PRIMARY KEY REFERENCES tenants(id) ON DELETE CASCADE,
        credits INTEGER DEFAULT 0 NOT NULL,
        credit_currency VARCHAR(10) DEFAULT 'RWF',
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    """)
    
    # Add an index to make balance lookups faster
    op.execute("CREATE INDEX idx_billing_accounts_tenant ON billing_accounts(tenant_id);")

def downgrade():
    op.execute("DROP TABLE IF EXISTS billing_accounts;")